### ISSUE TITLE
Home tab not updating

### ISSUE THREAD

**Issue by Elitesparkle** [HeroesToolChest/HeroesMatchTracker#22]
The list of replays in the Home tab is not updating, unless restarting the software ~~or using the Search button for most of the tabs in the Matches tab~~.

**Comment by koliva8245** [comment]
The Home tab only shows the **latest** replays (up to 20), but won't update for those out of order.

So for example if the last replay you parsed was on July 17, 2018 at 3:00pm (which will show up first on the list) and then you parsed a replay on the date at an earlier time, say 2:00pm, it will not show up, unless of course you restart the app.


Although I don't quite like it, it is working as intended.

**Comment by Elitesparkle** [comment]
> Although I don't quite like it, it is working as intended.

I see.

I noticed also it's slow at updating, as my last game is usually missing.

It would be useful to have a button to force an update without restarting.

**Comment by koliva8245** [comment]
Your last game never shows up?

The Home tab gets the latest replay data every 2 seconds.

**Comment by koliva8245** [comment]
I'm thinking that all your replays are not being successfully parsed. Go to the `Replay Parser` tab and see if there are any replays in the `View Failed Replays`. Or set the `Latest/Last` parse date time options to some X days ago to attempt a re-parse.

**Comment by koliva8245** [comment]
I'll keep on eye on this.  I need to be able to reproduce this in order to fix it.

**Comment by koliva8245** [comment]
I've acutally seen this before, but I'm not going to fix it.
