### ISSUE TITLE
HotsApi.net is not processing uploads correctly

### ISSUE THREAD

**Issue by ldaptv** [HeroesToolChest/HeroesMatchTracker#26]
I just wanted to make you aware that hotsapi.net is not processing uploads correctly.

The developers for Heroesprofile.net and the new HotsLogs.com which used to pull from hotsapi.net have worked together to develop "forks" of the hotsapi.net repositories to populate their sites with data.  Their uploader now uploads to both sites as well.

The community coordinates activities on this discord, I am sure they would love to have you join.
https://discord.gg/tA8jrc2

I love your app and use it all the time, so just wanted to make you aware of the recent developments and maybe encourage you to add the functions to upload to these two sites as well.

**Comment by koliva8245** [comment]
I"ll update the end point eventually.
