### ISSUE TITLE
Statistics: Parties doesn't seem to calculate properly

### ISSUE THREAD

**Issue by AndrewPalozzo** [HeroesToolChest/HeroesMatchTracker#27]
Seems like the parties calculation under statistics isn't calculating correctly.

1. Battletag vs just player name seems to do weird things
2. When entering my battletag alone it has a total of 10 games however the matches indicates over 100.
3. Adding another player into the mix just adds more randomness to the calculations.

**Comment by koliva8245** [comment]
Seems to be working fine for me. Verify you have the correct season and draft modes selected along with the `All in a Party` option. Should probably post some screenshots.

Things to keep in mind
- Having just your battletag entered and selected will find all your solo games (`All in a Party` unchecked, having it checked will always return 0 games)
- Having additional players selected, but empty battletag will find parties (`All in a Party`  checked) with any player name
  - So having three players check and only your battletag entered will find all 3 stacks you were part of
  - Having three players check and all battletags entered will find only 3 stacks of those player names

**Comment by AndrewPalozzo** [comment]
So it's pretty random the stats, so hard to properly quantify entirely. I'll post some screenshots of examples

1. Parties (my battletag only): 
![image](https://user-images.githubusercontent.com/4724681/87875797-26121800-ca17-11ea-9678-93ef4c17e8d4.png) vs overview stats: https://imgur.com/2NzbAio
![image](https://user-images.githubusercontent.com/4724681/87875802-30341680-ca17-11ea-9663-3dc157426db8.png)
- It shows 282 total games for this season when overview shows 177 total games
- Also note BattleTag not found.

1a. Changing to US region (I'm in Australia so we connect via US) removes the error but only shows 11 total games.  All the other regions show 282 games and 'BattleTag not found' error. ![image](https://user-images.githubusercontent.com/4724681/87875824-58237a00-ca17-11ea-9d99-e9e3e7bf87f7.png)


2. Party search without selecting 'all in party' ![image](https://user-images.githubusercontent.com/4724681/87875839-696c8680-ca17-11ea-8628-dc39545fcb1d.png)
- Shows 0 matches

3. Selecting 'all in party' shows matches: https://imgur.com/KEnbdAV
![image](https://user-images.githubusercontent.com/4724681/87875860-83a66480-ca17-11ea-8d9f-7c65972e8121.png)
- Only a few games are shown. We've played many many more
- Here's the quick match search showing lots of games together: ![image](https://user-images.githubusercontent.com/4724681/87875737-a6844900-ca16-11ea-8ff6-4f29aad575fa.png)

4. Stats are inaccurate. I've never played Ana before.
![image](https://user-images.githubusercontent.com/4724681/87875762-d92e4180-ca16-11ea-83e6-d8ab4637e5d5.png)
All matches search for Ana games: 
![image](https://user-images.githubusercontent.com/4724681/87875785-0c70d080-ca17-11ea-8159-76519f6fb5ca.png)

**Comment by koliva8245** [comment]
If the region isn't select it actually defaults to XX (ptr) and if you get a BattleTag not found, then it defaults to an empty battletag (basically treated as any player).

1a. It's correct? its the same stat shown in the overview (11 games).
2. That query will show matches that you two were not part of a party (both solo in the same match)
3. Interesting. On the matches screen shot, change the `Player Party` dropdown to `2 Stack` and check `For given BattleTag only`. Also on the party screen deselect all games modes except `Quick Match`.
4. BattleTags not found, it's searching for any player name (in this case it's searching for any two player names that are in a party with one player being Ana)

**Comment by AndrewPalozzo** [comment]
1a. No, don't think it's correct. Given I've just learned how the search works (It considers the number of players ticked when searching) In example 1a, it should be just solo queue stats no? In which case I've played 1 match solo this season

2. OK, makes sense  
3. OK, that all makes sense now 👍
I guess my only issue there was it wasn't clear that the 'parties stats' were limiting the search to the number of players ticked. But i love the way that's designed now that I get it. Since we can use this search to understand different party effects
4. OK makes sense given the above 👍

That all said, I don't care about 1a anyway, since the app is loaded with wayyyyy better stats for solo information already. I'm happy to troubleshoot further if you like though :)

**Comment by AndrewPalozzo** [comment]
Actually I might make one suggestion for enhancement now though, playing with a bit more.

In the example of scenario 3, I think it would be great to have a search not limit to the number of players selected.
At the moment i play with a lot of different friends. I would love to be able to see how me and one other friend have performed irrespective of size of the party. To do this at the moment I need to tick all the other player names (leave them blank and calculate the wins/losses). So something like 'minimum in party'? not sure how you name it :P

**Comment by koliva8245** [comment]
1a. Yes it should be solo queue stats. You can verify it by just searching on the match page for a single game mode.

Yes I see what you mean by the minimum in party. I'll see if I can include an option for that.

**Comment by AndrewPalozzo** [comment]
Yeah for 1a, stats seem a bit wonky as my solo matches are just 1 this season, but the parties search is showing 11.
Parties: ![image](https://user-images.githubusercontent.com/4724681/87890936-bd10bb80-ca7b-11ea-9ff5-90e92b8fad21.png)
All matches: ![image](https://user-images.githubusercontent.com/4724681/87890971-d31e7c00-ca7b-11ea-8f7d-b3c0399b378b.png)
