### ISSUE TITLE
Error pops up when looking at past matches

### ISSUE THREAD

**Issue by Lovestud500** [HeroesToolChest/HeroesMatchTracker#32]
![image](https://user-images.githubusercontent.com/88293127/127786980-473e1ef1-ab53-47b6-b81d-a4adf1fc2e36.png)

**Comment by koliva8245** [comment]
Are you able to attach a replay of that match? If not, can you say what build number that match is?

**Comment by Lovestud500** [comment]
![image](https://user-images.githubusercontent.com/88293127/128642283-f28d9ea0-b32f-46e3-8fde-891f151d1b26.png)

**Comment by Lovestud500** [comment]
[2021-05-03 19.40.30 Towers of Doom.zip](https://github.com/HeroesToolChest/HeroesMatchTracker/files/6951371/2021-05-03.19.40.30.Towers.of.Doom.zip)
(try this)

**Comment by koliva8245** [comment]
Fixed, I accidently skipped adding the hero data for 84249.

**Comment by Lovestud500** [comment]
Thank you. love the program. Please keep it up.
